<template>
  <div class="business-page">
    <header class="page-heading"><div><p class="eyebrow">B2B OPERATIONS</p><h1>报价、订单与发票</h1><p>处理经销商提交的业务单据；系统只允许按既定状态机流转。</p></div><el-button :loading="loading" @click="load"><el-icon><Refresh /></el-icon>刷新</el-button></header>
    <el-tabs v-model="activeTab" class="page-card" @tab-change="changeTab">
      <el-tab-pane label="报价请求" name="quotes">
        <div class="toolbar"><el-select v-model="status" clearable placeholder="全部报价状态" @change="search"><el-option v-for="option in quoteStatuses" :key="option.value" :label="option.label" :value="option.value" /></el-select><span>回复后金额和有效期作为报价版本快照展示给经销商。</span></div>
        <el-table v-loading="loading" :data="items" stripe empty-text="暂无报价请求"><el-table-column prop="quoteNo" label="报价编号" min-width="190" /><el-table-column prop="companyName" label="经销商企业" min-width="210" show-overflow-tooltip /><el-table-column label="商品" width="80"><template #default="{row}">{{row.itemCount}} 项</template></el-table-column><el-table-column label="期望交期" width="130"><template #default="{row}">{{formatBusinessDate(row.requestedDeliveryDate)}}</template></el-table-column><el-table-column label="报价金额" width="140"><template #default="{row}">{{row.totalAmount==null?'待报价':formatCurrency(row.totalAmount)}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="dealerStatusType(row.status)" effect="plain">{{dealerStatusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="110" fixed="right"><template #default="{row}"><el-button link type="primary" :disabled="row.status!=='SUBMITTED'" @click="openQuote(row)">{{row.status==='SUBMITTED'?'回复报价':'已处理'}}</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="经销商订单" name="orders">
        <div class="toolbar"><el-select v-model="status" clearable placeholder="全部订单状态" @change="search"><el-option v-for="option in orderStatuses" :key="option.value" :label="option.label" :value="option.value" /></el-select><span>订单状态顺序：待平台确认 → 已确认 → 已发货 → 已完成；取消后不可恢复。</span></div>
        <el-table v-loading="loading" :data="items" stripe empty-text="暂无经销商订单"><el-table-column prop="orderNo" label="订单编号" min-width="190" /><el-table-column prop="companyName" label="经销商企业" min-width="200" show-overflow-tooltip /><el-table-column prop="poNumber" label="PO Number" min-width="140"><template #default="{row}">{{row.poNumber||'-'}}</template></el-table-column><el-table-column label="金额" width="140"><template #default="{row}"><strong class="amount">{{formatCurrency(row.totalAmount)}}</strong></template></el-table-column><el-table-column label="状态" width="120"><template #default="{row}"><el-tag :type="dealerStatusType(row.status)" effect="plain">{{dealerStatusText(row.status)}}</el-tag></template></el-table-column><el-table-column prop="trackingNo" label="物流单号" min-width="150"><template #default="{row}">{{row.trackingNo||'-'}}</template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><div class="row-actions"><el-button v-if="row.status==='PENDING_REVIEW'" link type="primary" @click="changeOrder(row,'CONFIRMED')">确认订单</el-button><el-button v-if="row.status==='CONFIRMED'" link type="primary" @click="openShipment(row)">登记发货</el-button><el-button v-if="row.status==='SHIPPED'" link type="primary" @click="changeOrder(row,'COMPLETED')">完成</el-button><el-button v-if="['PENDING_REVIEW','CONFIRMED'].includes(row.status)" link type="danger" @click="changeOrder(row,'CANCELLED')">取消</el-button><span v-if="['COMPLETED','CANCELLED'].includes(row.status)" class="muted">无可用操作</span></div></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="发票与结算" name="invoices">
        <div class="toolbar"><el-select v-model="status" clearable placeholder="全部发票状态" @change="search"><el-option label="待处理" value="ISSUED" /><el-option label="已付款" value="PAID" /><el-option label="已作废" value="VOID" /></el-select><span>已付款或已作废的发票不可再次修改。</span></div>
        <el-table v-loading="loading" :data="items" stripe empty-text="暂无发票"><el-table-column prop="invoiceNo" label="发票编号" min-width="180" /><el-table-column prop="orderNo" label="关联订单" min-width="180" /><el-table-column prop="companyName" label="经销商企业" min-width="210" show-overflow-tooltip /><el-table-column label="金额" width="140"><template #default="{row}"><strong class="amount">{{formatCurrency(row.amount)}}</strong></template></el-table-column><el-table-column label="开具 / 到期" min-width="190"><template #default="{row}"><div class="stack-cell"><strong>{{formatBusinessDate(row.issuedAt)}}</strong><span>{{formatBusinessDate(row.dueAt)}}</span></div></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="dealerStatusType(row.status)" effect="plain">{{dealerStatusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button v-if="row.status==='ISSUED'" link type="primary" @click="changeInvoice(row,'PAID')">标记已付款</el-button><el-button v-if="row.status==='ISSUED'" link type="danger" @click="changeInvoice(row,'VOID')">作废</el-button><span v-else class="muted">已归档</span></template></el-table-column></el-table>
      </el-tab-pane>
      <el-pagination v-if="total>pageSize" v-model:current-page="page" :page-size="pageSize" :total="total" layout="total, prev, pager, next" @current-change="load" />
    </el-tabs>

    <el-dialog v-model="quoteDialog" title="回复报价请求" width="590px" append-to-body><el-descriptions v-if="selected" :column="1" border><el-descriptions-item label="报价编号">{{selected.quoteNo}}</el-descriptions-item><el-descriptions-item label="经销商企业">{{selected.companyName}}</el-descriptions-item><el-descriptions-item label="经销商备注">{{selected.notes||'-'}}</el-descriptions-item></el-descriptions><el-form ref="quoteFormRef" :model="quoteForm" :rules="quoteRules" label-position="top" class="dialog-form"><el-form-item label="处理结果" prop="action"><el-segmented v-model="quoteForm.action" :options="[{label:'给出报价',value:'QUOTED'},{label:'拒绝询价',value:'REJECTED'}]" /></el-form-item><div v-if="quoteForm.action==='QUOTED'" class="form-row"><el-form-item label="含税报价金额（¥）" prop="totalAmount"><el-input-number v-model="quoteForm.totalAmount" :min="0.01" :max="99999999" :precision="2" /></el-form-item><el-form-item label="报价有效期" prop="validUntil"><el-date-picker v-model="quoteForm.validUntil" type="date" value-format="YYYY-MM-DD" :disabled-date="disablePast" /></el-form-item></div><el-form-item label="平台说明" prop="platformNote"><el-input v-model="quoteForm.platformNote" type="textarea" :rows="4" maxlength="1000" show-word-limit :placeholder="quoteForm.action==='REJECTED'?'说明无法报价的原因':'填写税费、运费、交付与付款条款'" /></el-form-item></el-form><template #footer><el-button @click="quoteDialog=false">取消</el-button><el-button :type="quoteForm.action==='REJECTED'?'danger':'primary'" :loading="saving" @click="submitQuoteDecision">确认提交</el-button></template></el-dialog>
    <el-dialog v-model="shipmentDialog" title="登记订单发货" width="480px" append-to-body><el-form ref="shipmentFormRef" :model="shipmentForm" :rules="shipmentRules" label-position="top"><el-form-item label="订单编号"><el-input :model-value="selected?.orderNo" disabled /></el-form-item><el-form-item label="物流单号" prop="trackingNo"><el-input v-model="shipmentForm.trackingNo" maxlength="64" placeholder="请输入承运商物流单号" /></el-form-item></el-form><template #footer><el-button @click="shipmentDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitShipment">确认发货</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { dealerApi } from '../../services/dealer'
import { dealerStatusText, dealerStatusType, formatBusinessDate, formatCurrency } from '../../utils/dealer'

/** B2B 管理工作台按后端状态机展示动作，避免管理员跳过业务环节。 */
const activeTab=ref('quotes');const status=ref('');const page=ref(1);const pageSize=20;const total=ref(0);const items=ref([]);const loading=ref(false);const saving=ref(false);const selected=ref(null);const quoteDialog=ref(false);const shipmentDialog=ref(false);const quoteFormRef=ref(null);const shipmentFormRef=ref(null)
const quoteStatuses=[{label:'已提交',value:'SUBMITTED'},{label:'待经销商确认',value:'QUOTED'},{label:'已接受',value:'ACCEPTED'},{label:'已拒绝',value:'REJECTED'},{label:'已过期',value:'EXPIRED'}];const orderStatuses=[{label:'待平台确认',value:'PENDING_REVIEW'},{label:'已确认',value:'CONFIRMED'},{label:'已发货',value:'SHIPPED'},{label:'已完成',value:'COMPLETED'},{label:'已取消',value:'CANCELLED'}]
const quoteForm=reactive({action:'QUOTED',totalAmount:null,validUntil:'',platformNote:''});const shipmentForm=reactive({trackingNo:''})
const quoteRules={action:[{required:true,message:'请选择处理结果',trigger:'change'}],totalAmount:[{validator:(_r,v,done)=>quoteForm.action!=='QUOTED'||Number(v)>0?done():done(new Error('请填写大于 0 的报价金额')),trigger:'change'}],validUntil:[{validator:(_r,v,done)=>quoteForm.action!=='QUOTED'||v?done():done(new Error('请选择报价有效期')),trigger:'change'}],platformNote:[{required:true,message:'请填写平台说明',trigger:'blur'},{min:5,message:'平台说明至少 5 个字符',trigger:'blur'}]};const shipmentRules={trackingNo:[{required:true,message:'请填写物流单号',trigger:'blur'},{min:4,max:64,message:'物流单号长度为 4–64 个字符',trigger:'blur'}]}
async function load(){loading.value=true;try{const method={quotes:'adminQuotes',orders:'adminOrders',invoices:'adminInvoices'}[activeTab.value];const data=(await dealerApi[method]({status:status.value||undefined,page:page.value,pageSize})).data;items.value=data.items||[];total.value=data.total||0}catch(reason){ElMessage.error(reason.message||'业务单据加载失败')}finally{loading.value=false}}
function changeTab(){status.value='';page.value=1;load()}function search(){page.value=1;load()}function disablePast(date){return date.getTime()<new Date().setHours(0,0,0,0)}
function openQuote(row){selected.value=row;Object.assign(quoteForm,{action:'QUOTED',totalAmount:null,validUntil:'',platformNote:''});quoteDialog.value=true}
async function submitQuoteDecision(){if(!(await quoteFormRef.value?.validate().catch(()=>false)))return;try{await ElMessageBox.confirm(`确认${quoteForm.action==='QUOTED'?'向经销商提交正式报价':'拒绝该询价'}？提交后本报价请求不可再次处理。`,'确认报价处理',{type:'warning',confirmButtonText:'确认提交',cancelButtonText:'取消'});saving.value=true;await dealerApi.decideQuote(selected.value.quoteNo,{action:quoteForm.action,totalAmountFen:quoteForm.action==='QUOTED'?Math.round(Number(quoteForm.totalAmount)*100):undefined,validUntil:quoteForm.action==='QUOTED'?quoteForm.validUntil:undefined,platformNote:quoteForm.platformNote.trim()});ElMessage.success('报价处理结果已保存');quoteDialog.value=false;await load()}catch(reason){if(reason!=='cancel'&&reason!=='close')ElMessage.error(reason.message||'报价处理失败')}finally{saving.value=false}}
async function changeOrder(row,next){const labels={CONFIRMED:'确认订单',COMPLETED:'完成订单',CANCELLED:'取消订单'};try{await ElMessageBox.confirm(`确定要${labels[next]}“${row.orderNo}”吗？`,'确认订单状态',{type:next==='CANCELLED'?'warning':'info',confirmButtonText:'确认',cancelButtonText:'取消'});await dealerApi.updateOrderStatus(row.orderNo,{status:next});ElMessage.success('订单状态已更新');await load()}catch(reason){if(reason!=='cancel'&&reason!=='close')ElMessage.error(reason.message||'订单更新失败')}}
function openShipment(row){selected.value=row;shipmentForm.trackingNo='';shipmentDialog.value=true}async function submitShipment(){if(!(await shipmentFormRef.value?.validate().catch(()=>false)))return;saving.value=true;try{await dealerApi.updateOrderStatus(selected.value.orderNo,{status:'SHIPPED',trackingNo:shipmentForm.trackingNo.trim()});ElMessage.success('发货信息已登记');shipmentDialog.value=false;await load()}catch(reason){ElMessage.error(reason.message||'发货登记失败')}finally{saving.value=false}}
async function changeInvoice(row,next){try{await ElMessageBox.confirm(next==='VOID'?`作废发票“${row.invoiceNo}”后不可恢复。`:`确认发票“${row.invoiceNo}”已完成付款？`,next==='VOID'?'作废发票':'确认付款',{type:'warning',confirmButtonText:'确认',cancelButtonText:'取消'});await dealerApi.updateInvoiceStatus(row.invoiceNo,next);ElMessage.success('发票状态已更新');await load()}catch(reason){if(reason!=='cancel'&&reason!=='close')ElMessage.error(reason.message||'发票更新失败')}}
onMounted(load)
</script>

<style scoped>
.business-page{min-width:0}.page-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:18px}.eyebrow{margin:0 0 5px;color:var(--accent-color);font-size:10px;font-weight:800;letter-spacing:.15em}.page-heading h1{margin:0;font-size:25px}.page-heading p:last-child{margin:5px 0 0;color:var(--text-muted);font-size:13px}.page-card{padding:0 20px 20px;background:#fff;border:1px solid var(--border-color);border-radius:14px;box-shadow:var(--shadow-sm)}.toolbar{display:flex;align-items:center;gap:14px;margin:8px 0 15px;padding:12px;background:var(--bg-light);border-radius:10px}.toolbar .el-select{width:190px}.toolbar span,.muted{color:var(--text-light);font-size:10px}.amount{color:var(--accent-color);font-size:12px}.stack-cell{display:grid}.stack-cell strong{font-size:11px}.stack-cell span{color:var(--text-light);font-size:10px}.row-actions{display:flex;align-items:center;flex-wrap:wrap}.el-pagination{justify-content:flex-end;margin-top:17px}.dialog-form{margin-top:18px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}
@media(max-width:700px){.page-heading{align-items:flex-start;flex-direction:column}.page-card{padding:0 12px 15px}.toolbar{align-items:flex-start;flex-direction:column}.toolbar .el-select{width:100%}.form-row{grid-template-columns:1fr}.el-pagination{justify-content:flex-start;overflow-x:auto}}
</style>
