<template>
  <div class="security-page"><header class="page-heading"><div><p class="eyebrow">ACCOUNT SECURITY</p><h1>账户与安全</h1><p>维护个人联系人信息和登录密码；企业资料请在“企业 / 成员 / 地址”中修改。</p></div></header><div class="security-grid"><section class="form-card"><div class="card-head"><span class="card-icon"><el-icon><User /></el-icon></span><div><h2>个人资料</h2><p>用户名与登录邮箱不可在此修改。</p></div></div><el-form ref="profileFormRef" :model="profileForm" :rules="profileRules" label-position="top"><el-form-item label="用户名"><el-input :model-value="me?.username" disabled /></el-form-item><el-form-item label="登录邮箱"><el-input :model-value="me?.email" disabled /></el-form-item><el-form-item label="姓名" prop="realName"><el-input v-model="profileForm.realName" maxlength="64" /></el-form-item><el-form-item label="手机号" prop="phone"><el-input v-model="profileForm.phone" maxlength="32" /></el-form-item><el-button type="primary" :loading="profileSaving" @click="saveProfile">保存个人资料</el-button></el-form></section><section class="form-card"><div class="card-head"><span class="card-icon warning"><el-icon><Lock /></el-icon></span><div><h2>修改登录密码</h2><p>修改成功后请使用新密码重新登录。</p></div></div><el-alert title="密码至少 8 位，并同时包含大写字母、小写字母和数字。" type="info" :closable="false" show-icon /><el-form ref="passwordFormRef" :model="passwordForm" :rules="passwordRules" label-position="top" class="password-form"><el-form-item label="当前密码" prop="oldPassword"><el-input v-model="passwordForm.oldPassword" type="password" show-password autocomplete="current-password" /></el-form-item><el-form-item label="新密码" prop="newPassword"><el-input v-model="passwordForm.newPassword" type="password" show-password autocomplete="new-password" maxlength="128" /></el-form-item><el-form-item label="确认新密码" prop="confirmPassword"><el-input v-model="passwordForm.confirmPassword" type="password" show-password autocomplete="new-password" maxlength="128" /></el-form-item><el-button type="primary" :loading="passwordSaving" @click="savePassword">修改密码</el-button></el-form></section></div></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { authApi } from '../../services/auth'
/** 安全设置调用已有身份接口；密码不会保存到浏览器本地状态。 */
const me=ref(null);const profileFormRef=ref(null);const passwordFormRef=ref(null);const profileSaving=ref(false);const passwordSaving=ref(false);const profileForm=reactive({realName:'',phone:''});const passwordForm=reactive({oldPassword:'',newPassword:'',confirmPassword:''})
const profileRules={realName:[{max:64,message:'姓名不能超过 64 个字符',trigger:'blur'}],phone:[{pattern:/^$|^[0-9+\-()\s]{6,32}$/,message:'手机号格式不正确',trigger:'blur'}]};const passwordRules={oldPassword:[{required:true,message:'请输入当前密码',trigger:'blur'}],newPassword:[{required:true,message:'请输入新密码',trigger:'blur'},{min:8,max:128,message:'密码长度为 8–128 位',trigger:'blur'},{pattern:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/,message:'密码必须包含大写字母、小写字母和数字',trigger:'blur'}],confirmPassword:[{validator:(_r,v,done)=>v===passwordForm.newPassword?done():done(new Error('两次输入的新密码不一致')),trigger:'blur'}]}
async function load(){try{me.value=(await authApi.me()).data;profileForm.realName=me.value?.realName||'';profileForm.phone=me.value?.phone||''}catch(reason){ElMessage.error(reason.message||'账户资料加载失败')}}
async function saveProfile(){if(!(await profileFormRef.value?.validate().catch(()=>false)))return;profileSaving.value=true;try{me.value=(await authApi.updateProfile({...profileForm})).data;ElMessage.success('个人资料已保存')}catch(reason){ElMessage.error(reason.message||'资料保存失败')}finally{profileSaving.value=false}}
async function savePassword(){if(!(await passwordFormRef.value?.validate().catch(()=>false)))return;try{await ElMessageBox.confirm('修改密码后，建议退出并使用新密码重新登录。','确认修改密码',{type:'warning',confirmButtonText:'确认修改',cancelButtonText:'取消'});passwordSaving.value=true;await authApi.changePassword({oldPassword:passwordForm.oldPassword,newPassword:passwordForm.newPassword});Object.assign(passwordForm,{oldPassword:'',newPassword:'',confirmPassword:''});ElMessage.success('密码已修改')}catch(reason){if(reason!=='cancel'&&reason!=='close')ElMessage.error(reason.message||'密码修改失败')}finally{passwordSaving.value=false}}
onMounted(load)
</script>
<style scoped>
.page-heading{margin-bottom:20px}.eyebrow{margin:0 0 5px;color:var(--accent-color);font-size:10px;font-weight:800;letter-spacing:.15em}.page-heading h1{margin:0;font-size:25px}.page-heading p:last-child{margin:5px 0 0;color:var(--text-muted);font-size:13px}.security-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.form-card{padding:22px;background:#fff;border:1px solid var(--border-color);border-radius:15px;box-shadow:var(--shadow-sm)}.card-head{display:flex;align-items:center;gap:12px;margin-bottom:19px}.card-icon{width:40px;height:40px;display:grid;place-items:center;color:var(--primary-hover);background:var(--primary-light);border-radius:11px;font-size:19px}.card-icon.warning{color:var(--accent-color);background:#fbf1e9}.card-head h2{margin:0;font-size:17px}.card-head p{margin:2px 0 0;color:var(--text-light);font-size:10px}.password-form{margin-top:17px}@media(max-width:850px){.security-grid{grid-template-columns:1fr}}
</style>
