<template>
  <div class="support-page"><header class="page-heading"><div><p class="eyebrow">PARTNER SUPPORT</p><h1>客户支持</h1><p>提交采购、报价、物流或售后问题；工单会进入平台支持中心。</p></div></header><div class="support-grid"><section class="support-card"><h2>提交支持请求</h2><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="form-row"><el-form-item label="问题类型" prop="subject"><el-select v-model="form.subject"><el-option label="报价咨询" value="经销商报价咨询" /><el-option label="订单与物流" value="经销商订单与物流" /><el-option label="发票与结算" value="经销商发票与结算" /><el-option label="产品及资料" value="经销商产品及资料" /></el-select></el-form-item><el-form-item label="联系电话" prop="phone"><el-input v-model="form.phone" maxlength="32" /></el-form-item></div><el-form-item label="联系邮箱" prop="email"><el-input v-model="form.email" maxlength="128" /></el-form-item><el-form-item label="问题说明" prop="content"><el-input v-model="form.content" type="textarea" :rows="6" maxlength="2000" show-word-limit placeholder="请填写相关订单号、报价编号和需要协助的事项" /></el-form-item><el-button type="primary" :loading="submitting" @click="submit">提交支持请求</el-button></el-form></section><aside class="contact-card"><span>专属客户经理</span><strong>{{ company?.accountManager || '暂未分配' }}</strong><p>紧急业务问题可通过企业登记联系人与平台沟通。</p><dl><div><dt>企业联系人</dt><dd>{{company?.contactName||'-'}}</dd></div><div><dt>联系电话</dt><dd>{{company?.contactPhone||'-'}}</dd></div><div><dt>联系邮箱</dt><dd>{{company?.contactEmail||'-'}}</dd></div></dl><router-link to="/dealer/company">查看企业资料 →</router-link></aside></div></div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { supportApi } from '../../services/support'
import { useDealerStore } from '../../stores/dealer'
import { useUserStore } from '../../stores/user'
/** 经销商支持请求复用平台真实联系表单接口，不在前端制造独立假工单。 */
const dealerStore=useDealerStore();const userStore=useUserStore();const formRef=ref(null);const submitting=ref(false);const company=computed(()=>dealerStore.portalData?.company||null)
const form=reactive({name:'',email:'',phone:'',subject:'经销商订单与物流',content:''})
const required=(message)=>[{required:true,message,trigger:'blur'}];const rules={subject:required('请选择问题类型'),phone:[...required('请填写联系电话'),{pattern:/^[0-9+\-()\s]{6,32}$/,message:'联系电话格式不正确',trigger:'blur'}],email:[...required('请填写联系邮箱'),{type:'email',message:'邮箱格式不正确',trigger:'blur'}],content:[...required('请填写问题说明'),{min:10,message:'问题说明至少 10 个字符',trigger:'blur'}]}
async function submit(){if(!(await formRef.value?.validate().catch(()=>false)))return;submitting.value=true;try{await supportApi.submitMessage({...form});ElMessage.success('支持请求已提交');form.content=''}catch(reason){ElMessage.error(reason.message||'提交失败')}finally{submitting.value=false}}
onMounted(async()=>{if(!dealerStore.portalData)await dealerStore.fetchPortal().catch(()=>null);form.name=userStore.userInfo.username||'';form.email=company.value?.contactEmail||userStore.userInfo.email||'';form.phone=company.value?.contactPhone||''})
</script>
<style scoped>
.page-heading{margin-bottom:20px}.eyebrow{margin:0 0 5px;color:var(--accent-color);font-size:10px;font-weight:800;letter-spacing:.15em}.page-heading h1{margin:0;font-size:25px}.page-heading p:last-child{margin:5px 0 0;color:var(--text-muted);font-size:13px}.support-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:18px}.support-card,.contact-card{padding:22px;background:#fff;border:1px solid var(--border-color);border-radius:15px;box-shadow:var(--shadow-sm)}.support-card h2{margin:0 0 18px;font-size:17px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.contact-card{align-self:start;color:#fff;background:linear-gradient(145deg,#2b302f,#514a40);border:0}.contact-card>span{color:rgba(255,255,255,.56);font-size:11px}.contact-card>strong{display:block;margin:7px 0;font-size:22px}.contact-card>p{color:rgba(255,255,255,.62);font-size:11px}.contact-card dl{margin:19px 0}.contact-card dl>div{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid rgba(255,255,255,.12);font-size:11px}.contact-card dt{color:rgba(255,255,255,.48)}.contact-card dd{margin:0;text-align:right}.contact-card a{font-size:11px;font-weight:700;color:#fff}
@media(max-width:850px){.support-grid{grid-template-columns:1fr}}@media(max-width:560px){.form-row{grid-template-columns:1fr}}
</style>
